#!/usr/bin/env bash

#SBATCH --job-name="adLR"

#SBATCH --output=./reports/arrayJob_%A_%a.out
#SBATCH --error=./reports/arrayJob_%A_%a.err

#SBATCH --array=1-2%1

#SBATCH --gres=gpu:1
#SBATCH --ntasks=10
#SBATCH --mem=16G
#SBATCH --time=2-00:00
##SBATCH --time=0-00:10

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=pmirbach

python3.6 Main.py -id $SLURM_ARRAY_TASK_ID
##python3.6 comet_ml_test.py
##python3.6 NeuralNetworks.py
