#!/usr/bin/env bash

#SBATCH --job-name="adLR"

#SBATCH --output=./reports/test/arrayJob_%A_%a.out
#SBATCH --error=./reports/test/arrayJob_%A_%a.err

##SBATCH --array=1-160%4
#SBATCH --array=0-320:11%2

#SBATCH --gres=gpu:1
#SBATCH --ntasks=20
#SBATCH --mem=32G
#SBATCH --time=2-00:00
##SBATCH --time=0-00:10

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=pmirbach

for i in $(seq 0 10); do
    x=$(($SLURM_ARRAY_TASK_ID+$i))
    python3.6 Main.py -d fashion-mnist -id $x &
    sleep 1
    pids[$x]=$!
done

# wait for all pids
for pid in ${pids[*]}; do
    wait $pid
done

##python3.6 NeuralNetworks.py


