#!/usr/bin/env bash

#SBATCH --job-name="adLR"

#SBATCH --output=./reports/arrayJob_%A_%a.out
#SBATCH --error=./reports/arrayJob_%A_%a.err

##SBATCH --array=1-160%4
#SBATCH --array=1-20%4

#SBATCH --gres=gpu:1
#SBATCH --ntasks=10
#SBATCH --mem=16G
#SBATCH --time=2-00:00
##SBATCH --time=0-00:10

#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=pmirbach

python3.6 Main.py -d cifar10 -id $SLURM_ARRAY_TASK_ID &
pids[$SLURM_ARRAY_TASK_ID]=$!

# wait for all pids
for pid in ${pids[*]}; do
    wait $pid
done

##python3.6 NeuralNetworks.py
